### ISSUE TITLE
Nested Menus

### ISSUE THREAD

**Issue by Moregaze** [Tischel/TPie#18]
Idk if this is really an issue, but it would be great to have a way to go back to the original window if you entered the wrong one.  I have yet to find a way to make this work. 

Example Case:

Having a gear change pie with each role being a nested menu in which the actual jobs sit.  Either by macro switching or gearset equipping.  If you enter say Tanks but meant to go to Healers there is no way to go back to the main from within the nested menu.  

Let me know if I am missing something, if not I would love to see a return to top option, or a go back one menu.

**Comment by Tischel** [comment]
This won't be added because it brings too many complications.
You can manually add a "back" option by adding the original ring as a nested ring on the second one.

For example, lets say you have ring A that can go to ring B or C.
If you add ring A in both B and C, you'll essentially get a way to go back to A. If I'm understanding correctly this is what you want. You'll just have to do it manually.
