### ISSUE TITLE
Bug with "keep previous ring center"

### ISSUE THREAD

**Issue by chimera74** [Tischel/TPie#23]
Since the last plugin update my nested rings appear at the edge of the screen.
![tpie](https://user-images.githubusercontent.com/3358677/149349656-6dacb734-2aaa-422a-8c3c-c1fa9a24703c.gif)
If it is not a common bug then it has something to do with my setup - Dual display, game on the secondary one, on the right, borderless window.
Old behavior without "keep previous ring center" is still ok.

**Comment by Zenith-One** [comment]
Looking at the code, it seems the most likely culprit is [this bit](https://github.com/Tischel/TPie/commit/7827ce3b6fb4725fddd1a25afaf7a3dfe54364bf#diff-67b8cd9381e759f5bc80406897d4a500bb674cf76412022dee5c736fb543e925R372-R375).

I think the problem is that the code takes the coordinates of the center of the circle in the context of the FF window and then moves the mouse to those coordinates. However I think `SetCursorPos` uses system display as its baseline, not the FF window. In order to achieve the correct behavior using that method, I think you would need to somehow figure out where the FF window lives and then do some math.

Alternately if it is possible to check where the mouse position is in the FF window, you could find the difference between the mouse position in the FF window and the desired position to move it to within the FF window. Then, figure out the global mouse x/y, and apply the same difference to it.

For example, if the center of the pie should be at (50,50) in the FF window, but the mouse is at (30,60), the desired change would be (20,-10). Then, you find the global mouse x,y is say (1020, 986). So you set the mouse cursor position to (1040, 976)

**Comment by Tischel** [comment]
It is as you say.
I'll take a look at it eventually, for now disable the option 🙏 .

**Comment by Zenith-One** [comment]
This is officially my first c# commit ever. Hopefully it's useful to you :)
