### ISSUE TITLE
Suggestion: Click on nested icon

### ISSUE THREAD

**Issue by Imaginary-Narwhal** [Tischel/TPie#31]
Allow a setting to click on a nested icon instead of hover over for when using Toggleable rings. (Also in Ring Settings, you are missing the le in Toggleable, you currently have Toggable.)

**Comment by LegiXIV** [comment]
Been a year but I would really love this feature. Left click when you have nested rings inside a ring to get into further rather then hold it for x amount of time. would also make the user experience nicer since you still have to click to do an emote as an example. 
And maaaaaybe like a hotkey for going back to the former ring.

**Comment by nguyen-thienp** [comment]
I concur, and came here for exactly this feature

**Comment by Tischel** [comment]
Don't know how I missed this for so long.
Added a setting to Nested Ring Elements that lets you chose between clicking or hovering to activate.
Please note that this is unrelated to the keybind of the ring being toggleable or not.

Implemented in v1.9.1.0

**Comment by nguyen-thienp** [comment]
You're a hero, thank you so, so much! Works like a charm
