### ISSUE TITLE
Does not work at all any more

### ISSUE THREAD

**Issue by amaraame** [Tischel/TPie#49]
few days ago tpie just stopped working for me. I don't seem to have an issue with any other plugin and there are no updates to run. anyone else experiencing this?

**Comment by Tischel** [comment]
Not that I know of.

Please upload your dalamud log found in `%AppData%\XIVLauncher\dalamud.log`. If you don't want to upload it here, you can DM in discord (Tischel#5062).

Also please zip and upload your TPie settings folder found in `%AppData%\XIVLauncher\pluginConfigs\TPie`.

**Comment by Tischel** [comment]
It's the one named "dalamud" (you just cant see the extension).

**Comment by amaraame** [comment]
[dalamud.log](https://github.com/Tischel/TPie/files/11366180/dalamud.log)
ah, ok

**Comment by amaraame** [comment]
no font changes. I didn't even know that was an option. I just tried reinstalling it and now it opens at least. but all my rings are lost. thank you for the help.

**Comment by Tischel** [comment]
To be clear, changing fonts is not an option. TPie comes with a custom font that you can choose to use.
Regarding your rings, the settings you sent me already had no rings; so you somehow lost them before. Mostly because something went wrong and TPie corrupted your data.

I don't really know how this happened to be honest. Might be a good idea to backup your rings export in case this happens again.
